services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - kafka-net

  kafka:
    image: quay.io/debezium/kafka:3.0
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - kafka-net

  postgres:
    image: quay.io/debezium/postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - kafka-net

  connect:
    image: quay.io/debezium/connect:3.0
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      KEY_CONVERTER_SCHEMAS_ENABLE: "true"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "true"
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_CONSUMER_MAX_POLL_RECORDS: 2000 # increase to improve throughput
    volumes:
      - /Users/tosh/Desktop/Firebolt/debezium cdc/firebolt_jdbc_lib/firebolt-jdbc-3.6.2.jar
    ports:
      - "8083:8083"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
